services:
    app:
        image: kevinduy/php
        restart: always
        tty: true
        volumes:
            - ${APP_VOLUME}:/var/www/app
            - vendor-volume:/var/www/app/vendor
        working_dir: /var/www/app
        ports:
            - "8000:8000"
        links:
            - db
            - redis
        depends_on:
            - db
            - redis
        environment:
            - CHOKIDAR_USEPOLLING=true

    nginx:
        image: kevinduy/nginx
        restart: always
        tty: true
        volumes:
            - ${APP_VOLUME}:/var/www/app
            - ${APP_DOCKER}/nginx/conf.d:/etc/nginx/conf.d
            - ${APP_DOCKER}/nginx/install:/install
        ports:
            - "80:80"
            - "81:81"
        command: /bin/bash -c "nginx"

    db:
        image: mysql:8
        restart: always
        volumes:
            - ${APP_DOCKER_TMP}/db/mysql:/var/lib/mysql
            - ${APP_DOCKER_TMP}/db/data:/var/data
            - ${APP_DOCKER}/mysql/conf.d/db.cnf:/etc/mysql/conf.d/db.cnf
        working_dir: /var/data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis
        restart: always
        ports:
            - "6379:6379"
        volumes: 
            - ${APP_DOCKER_TMP}/redis/cache:/data
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

    minio:
        image: minio/minio
        container_name: minio
        volumes:
            - ${APP_DOCKER_TMP}/storage:/mnt/storage
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: password
        command: server --console-address ":9001" /mnt/storage

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
            PMA_USER_CONFIG_BASE64: PD9waHAKJGNmZ1snTG9naW5Db29raWVWYWxpZGl0eSddID0gODY0MDA7
        volumes:
            - ${APP_DOCKER_TMP}/phpmyadmin/sessions:/sessions

volumes:
    vendor-volume:
        driver: local